// slug | DfE subject-content refs shared by AQA 8300 and Edexcel 1MA1 | aqaSection | tierOnOtherBoards
//      | status | confidence | beyondCcea | cceaOnly | note
// tierOnOtherBoards: "F" = on the other boards' Foundation list, "H" = Higher only, "F+H" = both lists carry part
export const MATHS = [
// ---- M1 Number and algebra ----
["integers-ordering-and-inequality-symbols","N1;N2","3.1.1 Structure and calculation","F","matched","high","","",""],
["calculator-use-bidmas-and-inverse-operations","N3;N9","3.1.1 Structure and calculation","F","matched","high","","",""],
["factors-multiples-primes-squares-and-cubes","N4;N6","3.1.1 Structure and calculation","F","matched","high","","",""],
["place-value-and-decimals","N2","3.1.1 Structure and calculation","F","matched","high","","",""],
["rounding-and-money-notation","N13;N15","3.1.3 Measures and accuracy","F","matched","high","Error intervals in inequality notation (N15, Higher on both boards)","",""],
["equivalent-fractions-and-fraction-to-decimal","N10","3.1.2 Fractions, decimals and percentages","F","matched","high","","",""],
["adding-and-subtracting-fractions","N2;N8","3.1.1 Structure and calculation","F","matched","high","","",""],
["fraction-of-a-quantity","N12;R3","3.1.2 Fractions, decimals and percentages","F","matched","high","","",""],
["percentages-of-quantities","N12;R9","3.3 Ratio, proportion and rates of change","F","matched","high","","",""],
["percentage-increase-and-decrease","R9","3.3 Ratio, proportion and rates of change","F","matched","high","","",""],
["fractions-decimals-percentages-equivalence","N10;N12","3.1.2 Fractions, decimals and percentages","F","matched","high","","",""],
["money-and-simple-finance","N13;R9;R16","3.3 Ratio, proportion and rates of change","F","partial","medium","",
 "APR and AER by name, budgeting, wage slips and household finance vocabulary are a CCEA emphasis; N2's notes list household-finance terms but neither board examines APR/AER",""],
["algebraic-notation-and-vocabulary","A1;A3;A7","3.2.1 Notation, vocabulary and manipulation","F","matched","high","Inverse functions and composite functions (A7, Higher)","",""],
["collecting-like-terms-and-expanding-constant-brackets","A4","3.2.1 Notation, vocabulary and manipulation","F","matched","high","","",""],
["factorising-with-constant-common-factors","A4","3.2.1 Notation, vocabulary and manipulation","F","matched","high","","",""],
["writing-expressions-and-formulae-from-context","A21","3.2.3 Solving equations and inequalities","F","matched","high","","",""],
["substitution-and-standard-formulae","A2;A5","3.2.1 Notation, vocabulary and manipulation","F","matched","high","","",""],
["solving-linear-equations","A17","3.2.3 Solving equations and inequalities","F","matched","high","","",""],
["coordinates-and-plotting-straight-line-graphs","A8;A9","3.2.2 Graphs","F","matched","high","","",""],
["real-life-linear-graphs","A14","3.2.2 Graphs","F","matched","high","","",""],
// ---- M1 Geometry and measures ----
["geometric-vocabulary-notation-and-drawing","G1","3.4.1 Properties and constructions","F","matched","high","","",""],
["angles-at-a-point-and-on-a-line","G3","3.4.1 Properties and constructions","F","matched","high","","",""],
["angles-on-parallel-lines","G3","3.4.1 Properties and constructions","F","matched","high","","",""],
["circle-parts-and-vocabulary","G9","3.4.1 Properties and constructions","F","matched","high","","",""],
["triangles-and-quadrilaterals-properties-and-angles","G3;G4","3.4.1 Properties and constructions","F","matched","high","","",""],
["3d-shapes-nets-plans-and-elevations","G12;G13","3.4.1 Properties and constructions","F","matched","high","Constructing (rather than interpreting) plans and elevations (G13, Higher)","",""],
["metric-units-estimating-and-converting","N13;G14;R1","3.4.2 Mensuration and calculation","F","matched","high","","",""],
["time-timetables-and-measure-problems","N13;G14","3.4.2 Mensuration and calculation","F","matched","high","","",""],
["speed-and-compound-measures","R1;R11","3.3 Ratio, proportion and rates of change","F","matched","high","","",""],
["perimeter-and-area-rectangles-triangles-compound","G16;G17","3.4.2 Mensuration and calculation","F","matched","high","","",""],
["circumference-and-area-of-circles","G9;G17","3.4.2 Mensuration and calculation","F","matched","high","","",""],
["surface-area-and-volume-of-cubes-and-cuboids","G16;G17","3.4.2 Mensuration and calculation","F","matched","high","","",""],
// ---- M1 Handling data ----
["handling-data-cycle-sampling-surveys-and-bias","S1","3.6 Statistics","F","matched","high","","The handling-data cycle as a named framework is a CCEA emphasis; neither board names it",""],
["classifying-data-and-two-circle-venn-diagrams","P6;S2","3.5 Probability / 3.6 Statistics","F","matched","high","","",""],
["two-way-tables-and-extracting-data","S2","3.6 Statistics","F","matched","high","","",""],
["mean-median-mode-and-range","S4","3.6 Statistics","F","matched","high","","",""],
["averages-from-frequency-tables","S4","3.6 Statistics","F","matched","high","","",""],
["bar-charts-pictograms-pie-charts-and-line-graphs","S2;S3","3.6 Statistics","F","matched","high","","",""],
["frequency-trees-flow-charts-and-stem-and-leaf","P1;S2","3.5 Probability / 3.6 Statistics","F","partial","medium","",
 "Stem-and-leaf diagrams and flow charts: neither appears in the DfE reference list; both boards dropped stem-and-leaf from the 2015 content",""],
["comparing-distributions-patterns-and-exceptions","S4;S5","3.6 Statistics","F","matched","high","","",""],
["scatter-diagrams-and-correlation","S6","3.6 Statistics","F","matched","high","","",""],
// ---- M5 ----
["non-calculator-arithmetic","N2;N8","3.1.1 Structure and calculation","F","matched","high","","",""],
["estimation-and-approximation","N14","3.1.3 Measures and accuracy","F","matched","high","","",""],
["ratio-notation-and-simplifying","R4;R8","3.3 Ratio, proportion and rates of change","F","matched","high","","",""],
["dividing-a-quantity-in-a-ratio","R5","3.3 Ratio, proportion and rates of change","F","matched","high","","",""],
["proportion-best-buy-scaling-and-exchange-rates","R5;R7;R10;R11","3.3 Ratio, proportion and rates of change","F","matched","high","","",""],
["sequences-special-numbers-and-rules","A23;A24","3.2.4 Sequences","F","matched","high","Fibonacci-type, quadratic and geometric sequences including surd ratios (A24, Higher)","",""],
["real-life-graphs-conversion-and-distance-time","A14","3.2.2 Graphs","F","matched","high","","",""],
["reading-scales-accuracy-and-imperial-units","N13;N15;G14","3.1.3 Measures and accuracy","F","partial","medium","",
 "Imperial units: both boards state that imperial/metric conversions will be given in the question (N13 notes), so they are not examined as recall as CCEA examines them",""],
["maps-scale-drawings-and-accurate-drawing","R2;G15","3.3 / 3.4.1","F","matched","high","","",""],
["angle-sum-of-triangles-and-polygons","G3","3.4.1 Properties and constructions","F","matched","high","","",""],
["reflections-in-the-axes","G7;G8","3.4.1 Properties and constructions","F","matched","high","","",""],
["rotations-about-the-origin","G7;G8","3.4.1 Properties and constructions","F","matched","high","","",""],
["translations","G7;G8","3.4.1 Properties and constructions","F","matched","high","","",""],
["enlargements-positive-whole-number-scale-factor","G7;G19","3.4.1 Properties and constructions","F","matched","high","","",""],
["probability-vocabulary-and-scale","P1;P2;P3","3.5 Probability","F","matched","high","","",""],
["listing-outcomes-and-systematic-listing","N5;P7","3.1.1 / 3.5","F","matched","high","","",""],
["calculating-probabilities-and-expectation","P2;P4;P7;P8","3.5 Probability","F","matched","high","","",""],
// ---- M2 ----
["index-laws-for-numbers","N6;N7","3.1.1 Structure and calculation","F","matched","high","","",""],
["hcf-lcm-and-prime-factorisation","N4","3.1.1 Structure and calculation","F","matched","high","","",""],
["decimals-of-any-size-and-significant-figures","N2;N15","3.1.1 / 3.1.3","F","matched","high","","",""],
["recurring-decimals-and-fraction-to-decimal-conversion","N10","3.1.2 Fractions, decimals and percentages","F","matched","high","","",""],
["fraction-arithmetic-all-four-operations","N2;N8","3.1.1 Structure and calculation","F","matched","high","","",""],
["repeated-percentage-change-and-depreciation","R9;R16","3.3 Ratio, proportion and rates of change","F","matched","high","","",""],
["compound-interest-and-finance-problems","N13;R16","3.3 Ratio, proportion and rates of change","F","partial","medium","",
 "Insurance, tax and mortgage contexts are a CCEA emphasis; R16 covers compound interest only",""],
["expanding-and-factorising-with-a-single-term","A4","3.2.1 Notation, vocabulary and manipulation","F","matched","high","","",""],
["linear-equations-unknown-on-both-sides-and-fractions","A17;A21","3.2.3 Solving equations and inequalities","F","matched","high","","",""],
["midpoint-and-length-of-a-line-segment","A8;G11","3.2.2 / 3.4.1","F","matched","high","","",""],
["gradient-and-intercept-of-linear-graphs-in-context","A10;R14","3.2.2 Graphs","F","matched","high","","",""],
["density","R11;N13","3.3 Ratio, proportion and rates of change","F","matched","high","","",""],
["area-of-quadrilaterals-and-composite-shapes","G16","3.4.2 Mensuration and calculation","F","matched","high","","",""],
["volume-of-prisms-and-cylinders","G16;G17","3.4.2 Mensuration and calculation","F","matched","high","","",""],
["pythagoras-theorem-in-2d","G6;G20","3.4.2 Mensuration and calculation","F","matched","high","","",""],
["three-circle-venn-diagrams","P6","3.5 Probability","F","matched","high","","",""],
["estimated-mean-and-modal-class-from-grouped-data","S4","3.6 Statistics","F","matched","high","","",""],
["lines-of-best-fit-interpolation-outliers-and-causation","S6","3.6 Statistics","F","matched","high","","",""],
// ---- M6 ----
["binary-and-number-systems","","","","unmatched","high","",
 "Number bases and decimal-binary conversion appear nowhere in the DfE GCSE mathematics subject content, so in neither AQA 8300 nor Edexcel 1MA1. This is CCEA-only",
 "The nearest published material is Key Stage 3 computing, not GCSE mathematics."],
["index-laws-in-algebra","A4","3.2.1 Notation, vocabulary and manipulation","F","matched","high","","",""],
["trial-and-improvement","A20","3.2.3 Solving equations and inequalities","H","partial","medium","",
 "Trial and improvement was removed from the 2015 English content; A20 (iteration, Higher only) is the nearest equivalent and is a different technique",""],
["linear-inequalities-in-one-variable","A22","3.2.3 Solving equations and inequalities","F","matched","high","Quadratic inequalities and set notation (A22, Higher)","",""],
["changing-the-subject-of-a-simple-formula","A5","3.2.1 Notation, vocabulary and manipulation","F","matched","high","","",""],
["nth-term-of-linear-sequences","A25","3.2.4 Sequences","F","matched","high","nth term of a quadratic sequence (A25, Higher)","",""],
["simultaneous-equations-graphically","A19","3.2.3 Solving equations and inequalities","F","matched","high","","",""],
["plotting-quadratic-graphs","A11;A12;A18","3.2.2 / 3.2.3","F","matched","high","Turning points by completing the square (A11, Higher)","",
 "A11, A12 and the graphical part of A18 are all Foundation content on AQA and Edexcel; CCEA places this at M6."],
["bearings","G15","3.4.1 Properties and constructions","F","matched","high","","",""],
["interior-and-exterior-angles-of-polygons","G3","3.4.1 Properties and constructions","F","matched","high","","",""],
["transformation-properties-and-congruence","G5;G6;G7;G8","3.4.1 Properties and constructions","F","matched","high","","",""],
["reflections-in-any-vertical-or-horizontal-line-and-rotations-about-any-point","G7;G8","3.4.1 Properties and constructions","F","matched","high","","",""],
["translations-with-vector-notation","G7;G24;G25","3.4.1 / 3.4.3 Vectors","F","matched","high","Vector geometry proofs (G25, Higher)","",""],
["enlargement-and-its-effect-on-perimeter-and-area","G19;R12","3.4.1 / 3.3","F","matched","high","","",""],
["ruler-and-compass-constructions","G2","3.4.1 Properties and constructions","F","matched","high","","",""],
["loci-and-regions","G2","3.4.1 Properties and constructions","F","matched","high","","",""],
["sample-space-diagrams-for-two-events","P7","3.5 Probability","F","matched","high","","",""],
["relative-frequency-and-experimental-probability","P2;P3;P5","3.5 Probability","F","matched","high","","",""],
// ---- M3 (Higher) ----
["hcf-and-lcm-from-prime-factor-form","N4","3.1.1 Structure and calculation","F","matched","high","","",""],
["reverse-percentages","R9","3.3 Ratio, proportion and rates of change","F","matched","high","","",""],
["upper-and-lower-bounds-addition-and-multiplication","N15;N16","3.1.3 Measures and accuracy","H","matched","high","","",
 "N16 (limits of accuracy, including upper and lower bounds) is Higher only on both boards, as it is on CCEA."],
["identities-and-expanding-double-brackets","A3;A4;A6","3.2.1 Notation, vocabulary and manipulation","F","matched","high","Algebraic proof (A6, Higher)","",""],
["factorising-quadratics-x2-plus-bx-plus-c","A4;A18","3.2.1 / 3.2.3","F","matched","high","","",""],
["difference-of-two-squares","A4","3.2.1 Notation, vocabulary and manipulation","H","matched","high","","",""],
["algebraic-fractions-with-numerical-denominators","A4;A17","3.2.1 / 3.2.3","H","matched","high","","",""],
["simplifying-multiplying-and-dividing-algebraic-fractions","A4","3.2.1 Notation, vocabulary and manipulation","H","matched","high","","",""],
["solving-quadratic-equations-by-factorising","A18;A21","3.2.3 Solving equations and inequalities","F","matched","high","","",""],
["straight-lines-y-mx-c-equation-of-a-line-and-parallel-lines","A9;A10","3.2.2 Graphs","F+H","matched","high","","",
 "A9's parallel-line clause is Additional foundation; the perpendicular-line clause is Higher only."],
["circle-parts-arc-length-and-sector-area","G9;G18","3.4.1 / 3.4.2","H","matched","high","","",""],
["cylinder-cone-and-sphere-surface-area-and-volume","G17","3.4.2 Mensuration and calculation","H","matched","high","","",""],
["pressure","R11","3.3 Ratio, proportion and rates of change","H","matched","high","","",""],
["trigonometry-sohcahtoa-in-2d","G20;G21;G22","3.4.2 Mensuration and calculation","F+H","matched","high","Exact trigonometric values for 0, 30, 45, 60 and 90 degrees (G22, Higher)","",""],
["quartiles-and-interquartile-range-from-a-list","S4","3.6 Statistics","H","matched","high","","",""],
["cumulative-frequency-tables-and-curves","S3;S4","3.6 Statistics","H","matched","high","","",""],
["box-plots-and-comparing-distributions","S3;S4;S5","3.6 Statistics","H","matched","high","","",""],
// ---- M7 (Higher) ----
["surds-and-pi-in-exact-calculations","N8","3.1.1 Structure and calculation","F+H","matched","high","","",""],
["index-laws-zero-and-negative-powers","N7","3.1.1 Structure and calculation","F+H","matched","high","","",""],
["standard-form","N9","3.1.1 Structure and calculation","F","matched","high","","",""],
["index-laws-in-algebra-integer-powers","A4","3.2.1 Notation, vocabulary and manipulation","H","matched","high","","",""],
["simultaneous-equations-algebraically","A19","3.2.3 Solving equations and inequalities","F","matched","high","","",""],
["inequalities-in-two-variables-and-regions","A22","3.2.3 Solving equations and inequalities","H","matched","high","","",""],
["changing-the-subject-harder-formulae","A5","3.2.1 Notation, vocabulary and manipulation","H","matched","high","","",""],
["nth-term-of-non-linear-sequences","A24;A25","3.2.4 Sequences","H","matched","high","","",""],
["recognising-and-sketching-linear-quadratic-cubic-and-reciprocal-graphs","A12","3.2.2 Graphs","F+H","matched","high","Exponential and trigonometric graphs (A12, Higher)","",""],
["quadratic-graphs-and-intersections-with-straight-lines","A11;A12;A18;A19","3.2.2 / 3.2.3","F+H","matched","high",
 "Iteration (A20, Higher); completing the square to find the turning point (A11, Higher)","",
 "The graphical clauses of A18 and A19 are Additional foundation on both boards; CCEA sets this at M7 (Higher)."],
["direct-proportion","R10;R13;R14","3.3 Ratio, proportion and rates of change","F+H","matched","high","","",""],
["combined-transformations-and-reflections-in-y-equals-plus-or-minus-x","G7;G8","3.4.1 Properties and constructions","F+H","matched","high","","",""],
["enlargements-with-fractional-scale-factors","G7;G19","3.4.1 Properties and constructions","H","matched","high","","",""],
["similar-shapes-length-area-and-volume-scale-factors","G19;R12","3.4.1 / 3.3","H","matched","high","","",""],
["product-rule-for-counting","N5","3.1.1 Structure and calculation","H","matched","high","","",""],
["adding-and-multiplying-probabilities","P4;P8","3.5 Probability","F+H","matched","high","","",""],
["tree-diagrams-for-independent-events","P6;P8","3.5 Probability","F+H","matched","high","","",""],
// ---- M4 (Higher) ----
["upper-and-lower-bounds-subtraction-and-division","N16","3.1.3 Measures and accuracy","H","matched","high","","",""],
["factorising-harder-quadratics-ax2-plus-bx-plus-c","A4;A18","3.2.1 / 3.2.3","H","matched","high","","",""],
["algebraic-fractions-with-linear-denominators","A4;A17","3.2.1 / 3.2.3","H","matched","high","","",""],
["quadratic-formula-and-harder-quadratic-equations","A18;A21","3.2.3 Solving equations and inequalities","H","matched","high","Completing the square as a solving method (A18, Higher) is examined by both boards; CCEA does not require it","",""],
["perpendicular-lines","A9","3.2.2 Graphs","H","matched","high","","",""],
["frustums-and-compound-solids","G17","3.4.2 Mensuration and calculation","H","partial","medium","",
 "Frustums are not named in the DfE content; G17 (surface area and volume of spheres, pyramids, cones and composite solids) is the nearest reference and both boards do set frustum questions under it",""],
["circle-theorems","G10","3.4.1 Properties and constructions","H","partial","high",
 "Proving the circle theorems (G10 explicitly says 'apply and prove'); CCEA excludes the proofs and requires only their use with reasons","",""],
["stratified-sampling-and-population-estimates","S1","3.6 Statistics","H","partial","medium","",
 "Stratified sampling is not named in the DfE content; S1 (infer properties of populations from a sample) is the nearest reference. The capture-recapture population estimate is a CCEA emphasis",""],
["histograms-unequal-widths","S2;S3","3.6 Statistics","H","matched","high","","",""],
// ---- M8 (Higher) ----
["surds-simplifying-rationalising-and-irrational-numbers","N7;N8","3.1.1 Structure and calculation","H","matched","high","","",""],
["recurring-decimals-to-fractions","N10","3.1.2 Fractions, decimals and percentages","H","matched","high","","",""],
["fractional-and-negative-indices","N7","3.1.1 Structure and calculation","H","matched","high","","",""],
["growth-decay-and-exponential-graphs","A12;R16","3.2.2 / 3.3","H","matched","high","","",""],
["index-laws-in-algebra-fractional-and-negative-powers","A4","3.2.1 Notation, vocabulary and manipulation","H","matched","high","","",""],
["simultaneous-equations-linear-and-non-linear","A19","3.2.3 Solving equations and inequalities","H","matched","high","","",""],
["graphical-solution-of-quadratic-equations","A18;A19","3.2.3 Solving equations and inequalities","H","matched","high","","",
 "The rearrangement clause of A18 ('including those that require rearrangement') is Higher only on both boards and is the exact match for CCEA M8-NA-09."],
["gradient-of-a-curve-as-rate-of-change","A15;R15","3.2.2 / 3.3","H","matched","high","","",""],
["equation-of-a-circle-and-its-tangent","A16","3.2.2 Graphs","H","matched","high","","",""],
["inverse-proportion","R10;R13;R14","3.3 Ratio, proportion and rates of change","F+H","matched","high","","",""],
["sine-rule-cosine-rule-and-area-of-a-triangle","G22;G23","3.4.2 Mensuration and calculation","H","matched","high","","",""],
["pythagoras-and-trigonometry-in-3d","G20;G21","3.4.2 Mensuration and calculation","H","matched","high","","",""],
["enlargements-with-negative-scale-factors","G7;G19","3.4.1 Properties and constructions","H","matched","high","","",""],
["similar-3d-shapes-length-area-and-volume-ratios","G19;R12","3.4.1 / 3.3","H","matched","high","","",""],
["conditional-probability-and-tree-diagrams-without-replacement","P6;P8;P9","3.5 Probability","H","matched","high","","",""],
];
