// slug | aqaRefs (8464 unless prefixed) | edexcelRefs (1SC0) | status | confidence | beyondCcea | cceaOnly | note
// status: matched | partial | ccea-only | unmatched
export const SCIENCE = [
// ---------------- B1 ----------------
["b1-cells-and-microscopy","4.1.1.1;4.1.1.2;4.1.1.3;4.1.1.5","CB1.1;CB1.2;CB1.3;CB1.6","matched","high",
 "Electron microscopy and its history (AQA 4.1.1.5, Edexcel CB1.3); orders of magnitude and standard form for cell sizes (CB1.4, CB1.5)",
 "CCEA's magnification rule is eyepiece x objective; both other boards teach magnification = image size / real size only",
 "Edexcel CB1.6 is a Core Practical (microscopy with magnification calculations and scientific drawings) and is the closest match to CCEA's microscope work."],
["b1-photosynthesis-equation-limiting-factors","4.4.1.1;4.4.1.2","CB6.2;CB6.3;CB6.4","matched","high",
 "Inverse square law for light intensity (Edexcel CB6.6, Higher); greenhouse economics (AQA 4.4.1.2)","",
 "AQA words the limiting-factor interaction as graph interpretation; Edexcel CB6.4 asks for the interaction of all three factors."],
["b1-photosynthesis-investigations","4.4.1.2","CB6.5","matched","high","","CCEA Prescribed Practical B1 tests starch, light, CO2 and chlorophyll in one sequence; AQA RP5 and Edexcel CB6.5 vary light intensity only",
 "AQA required practical 5 and Edexcel Core Practical CB6.5 are both the light-intensity investigation."],
["b1-leaf-structure-gas-exchange","4.2.3.1;4.2.3.2","CB6.7;CB6.8","partial","high","",
 "Compensation point: zero hits in AQA 8464, AQA 8461 and Edexcel 1SC0","Leaf structure is taught on both boards as an exchange-surface argument."],
["b1-food-tests","4.2.2.1","","partial","high","","Edexcel's food-test Core Practical is in GCSE Biology 1BI0 only, not in Combined Science 1SC0",
 "AQA required practical 4 (food tests, Benedict's and Biuret named) sits inside 4.2.2.1 in Trilogy."],
["b1-biological-molecules-food-energy","4.2.2.1","","partial","medium","",
 "CCEA Prescribed Practical B2 (energy content of food by calorimetry) has no AQA required practical or Edexcel core practical equivalent","" ],
["b1-enzymes-and-digestion","4.2.2.1","CB1.7;CB1.12","matched","high","","","Edexcel CB1.7 names the active site and specificity explicitly, which is the cleanest statement of the lock-and-key idea."],
["b1-enzyme-factors","4.2.2.1","CB1.8;CB1.9;CB1.10;CB1.11","matched","high",
 "Rate calculations for enzyme activity as a named skill (Edexcel CB1.11)","Inhibitors: CCEA names them; AQA and Edexcel do not at this level",
 "AQA required practical 5 (effect of pH on amylase) and Edexcel Core Practical CB1.10 both match CCEA Prescribed Practical B3."],
["b1-respiratory-surfaces-breathing","4.4.2.2","CB8.1;CB8.2;CB8.3","partial","high",
 "Surface area : volume ratio as a calculation (Edexcel CB8.2)","","Edexcel's exchange-surface template (big, thin, good blood supply, gradient maintained) transfers directly."],
["b1-aerobic-respiration","4.4.2.1","CB8.9","matched","high","","",""],
["b1-anaerobic-respiration","4.4.2.1;4.4.2.2","CB8.10;CB8.11","matched","high",
 "Oxygen debt and the liver's role in removing lactic acid (AQA 4.4.2.2)","",""],
["b1-nervous-system-cns","4.5.2","CB2.13","matched","high","","",""],
["b1-reflex-arc","4.5.2","CB2.14","matched","high","","CCEA uses 'association neurone' where both other boards say 'relay neurone'",""],
["b1-blood-glucose-diabetes","4.5.1;4.5.3.1;4.5.3.2","CB7.1;CB7.9;CB7.13;CB7.15;CB7.16","matched","high",
 "Glucagon (Edexcel CB7.14); BMI and waist:hip calculations (CB7.17); negative feedback as a named mechanism (AQA 4.5.3.6)","",""],
["b1-kidney-osmoregulation","8461:4.5.3.3","","ccea-only","high","",
 "The kidney, ADH and osmoregulation are in AQA GCSE Biology 8461 only and in no Edexcel Combined Science statement","Against Combined Science this is CCEA-only; AQA Biology 8461 4.5.3.3 is the nearest published treatment."],
["b1-plant-hormones-phototropism","8461:4.5.4.1","","ccea-only","high","",
 "Plant hormones and phototropism are AQA Biology 8461 only (and biology-only there); zero hits in Edexcel 1SC0",""],
["b1-fieldwork-sampling","4.7.2.1","CB9.5;CB9.6","matched","high","","",
 "AQA required practical 9 (quadrats and transects) and Edexcel Core Practical CB9.5 both match CCEA Prescribed Practical B4."],
["b1-competition-food-webs","4.7.1.1;4.7.1.2;4.7.1.3;4.7.1.4;4.7.2.1","CB9.1;CB9.2;CB9.3;CB9.4","matched","high",
 "Parasitism and mutualism (Edexcel CB9.4)","",""],
["b1-decomposition-carbon-cycle","4.7.2.2","CB9.12;CB9.13","matched","high","","",""],
["b1-nitrogen-cycle","4.7.2.2","CB9.15","partial","medium","",
 "AQA Trilogy mentions the nitrogen cycle once inside 4.7.2.2; it is not a taught outcome",
 "The Edexcel statement is printed as CC9.15 in the specification but sits in the biology topic 9 list; treat as CB9.15."],
["b1-minerals-eutrophication","4.2.3.2","CB6.7;CB9.9","partial","high","",
 "Eutrophication: zero hits in AQA 8464 and 8461; Edexcel covers it only inside CB9.9 (human interactions in ecosystems)",""],
// ---------------- B2 ----------------
["b2-osmosis","4.1.3.2","CB1.15;CB1.16;CB1.17","matched","high",
 "Percentage gain and loss of mass as a named calculation (Edexcel CB1.17)",
 "Plasmolysis and turgidity: zero hits in AQA 8464/8461 and Edexcel 1SC0",
 "AQA required practical 3 and Edexcel Core Practical CB1.16 are both osmosis in potato, matching CCEA Prescribed Practical B5."],
["b2-transpiration-potometer","4.2.3.2","CB6.9;CB6.12;CB6.13","matched","high",
 "Translocation of sucrose (Edexcel CB6.10)","'Potometer' by name: zero hits in AQA 8464/8461 and Edexcel 1SC0, although both examine water uptake",""],
["b2-blood-and-vessels","4.2.2.2;4.2.2.3","CB8.6;CB8.7","matched","high","","Cell lysis is CCEA-specific vocabulary here",""],
["b2-heart-double-circulation","4.2.2.2;4.4.2.2","CB8.8;CB8.12","matched","high",
 "Cardiac output = stroke volume x heart rate (Edexcel CB8.12)","",""],
["b2-reproductive-systems","","","ccea-only","high","",
 "Male and female reproductive organ names and functions are KS3 in England; zero equivalent statements in AQA 8464, AQA 8461 or Edexcel 1SC0",
 "Nearest touchpoints only: AQA 4.5.3.3 names the ovary and testes as hormone sources; Edexcel CB7.1 names them as endocrine glands."],
["b2-fertilisation-pregnancy","4.1.1.3;4.1.1.4;4.6.1.2","CB1.2;CB3.3","partial","high",
 "Acrosome (Edexcel CB1.2a); the cell-membrane block to polyspermy (CB1.2b)",
 "Placenta, villi, umbilical cord, amnion and amniotic fluid: zero hits in all three specifications. Oviduct as the named site of fertilisation, and implantation as a taught step, are also CCEA-only",
 "AQA 4.6.1.2 carries the zygote to mitosis to differentiation chain inside its meiosis section."],
["b2-sex-hormones-menstrual-cycle","4.5.3.3","CB7.1;CB7.4","matched","high",
 "FSH and LH and their interactions (Edexcel CB7.5; AQA 4.5.3.3 Higher only) are beyond CCEA entirely; also the menopause and negative feedback","",
 "Edexcel CB7.4 (oestrogen and progesterone only) is the closest statement on any board to CCEA 2.3.5."],
["b2-infertility-contraception","4.5.3.4;4.5.3.5","CB7.6;CB7.7;CB7.8","matched","high",
 "Clomifene (Edexcel CB7.8); intrauterine devices, diaphragms, patches, spermicides and abstinence (AQA 4.5.3.4); 'inhibits FSH' as the pill's mechanism",
 "CCEA's mechanical / chemical / surgical classification, and the STI link (HIV, chlamydia) inside the contraception outcome",
 "CCEA 2.3.6 and AQA 4.5.3.5 are both Higher-only."],
["b2-genome-chromosomes-dna","4.1.2.1;4.6.1.3","CB3.4;CB3.5;CB3.13","matched","high",
 "DNA extraction from fruit (Edexcel CB3.6); the Human Genome Project (CB3.21); protein synthesis","",""],
["b2-mitosis-meiosis","4.1.2.2;4.6.1.2","CB2.1;CB2.2;CB2.3;CB3.3","matched","high",
 "The named stages of mitosis and the cell cycle (Edexcel CB2.1); stem cells (AQA 4.1.2.3, Edexcel CB2.8, CB2.9)",
 "AQA states that knowledge of the stages of meiosis is not required, as CCEA does",""],
["b2-monohybrid-genetics","4.6.1.4","CB3.13;CB3.14;CB3.16","matched","high",
 "Probability, ratio and percentage outcomes as a named calculation (Edexcel CB3.16)","",""],
["b2-sex-determination-genetic-conditions-screening","4.6.1.5;4.6.1.6","CB3.15","partial","high","",
 "Genetic screening: zero hits in AQA 8464/8461 and Edexcel 1SC0",""],
["b2-genetic-engineering","4.6.2.4","CB4.10;CB4.11;CB4.14","partial","high",
 "Ligase as a named stage (Edexcel CB4.11b); GM crops, herbicide and insect resistance, and the wild-flower and human-health concerns (AQA 4.6.2.4); gene therapy for inherited disorders",
 "Culturing the GM bacterium in a FERMENTER, and extraction, purification and packaging (downstreaming): zero hits for 'fermenter' or 'downstream' in AQA 8464, AQA 8461 and Edexcel 1SC0",
 "Edexcel CB4.10 is almost word for word CCEA's statement, and CB4.11 (restriction enzymes, ligase, sticky ends, vectors) is the closest match anywhere to CCEA's Higher detail - it is the right source for the sticky-end cut our Summer 2025 B2 Higher finding names. AQA's main-steps list is HT only, as CCEA's is."],
["b2-variation","4.6.2.1","CB3.19;CB3.20;CB3.22;CB3.23","partial","high",
 "Most phenotypic features result from multiple genes (Edexcel CB3.19); the relative effect sizes of mutations (CB3.23)",
 "CONTINUOUS and DISCONTINUOUS variation, and the histogram-versus-bar-chart distinction that goes with them: zero hits for 'continuous variation' or 'discontinuous' in AQA 8464, AQA 8461 and Edexcel 1SC0",
 "The causes of variation (genetic via mutation and sexual reproduction; environmental) are matched almost exactly by Edexcel CB3.20. The data-presentation half is CCEA-only and its nearest published home is GCSE Statistics."],
["b2-natural-selection-selective-breeding","4.6.2.2;4.6.2.3;4.6.3.3","CB4.2;CB4.8","matched","high",
 "Evidence for human evolution from fossils and stone tools (Edexcel CB4.4, CB4.5); the three-domain classification (CB4.7)","",""],
["b2-health-communicable-diseases-aseptic","4.3.1.1;4.3.1.2;4.3.1.3;4.3.1.4;4.3.1.5;4.2.2.5","CB5.1;CB5.2;CB5.3;CB5.4;CB5.5;CB5.6;CB5.8","partial","high",
 "Named diseases differ: AQA sets measles, HIV, TMV, salmonella, gonorrhoea, rose black spot and malaria; Edexcel sets cholera, TB, chalara and malaria",
 "Aseptic technique: AQA has it in Biology 8461 only (4.1.1.6, biology only) and Edexcel 1SC0 has none",""],
["b2-defence-mechanisms-immunity","4.3.1.6;4.3.1.7","CB5.12;CB5.13;CB5.14","partial","high",
 "Antitoxin production as a third white-blood-cell role (AQA 4.3.1.6); cilia and lysozyme as named chemical defences (Edexcel CB5.12); herd immunity (AQA 4.3.1.7)",
 "ACTIVE and PASSIVE immunity as named categories: zero hits for 'active immunity' or 'passive immunity' in AQA 8464, AQA 8461 and Edexcel 1SC0. Blood clotting as a barrier is also CCEA's own",
 "Edexcel CB5.13 is the best match on any board and is the one statement that names MEMORY LYMPHOCYTES and their role in the SECONDARY RESPONSE (parts c and d) - exactly the content our Summer 2025 B2 Foundation finding says was explained vaguely. AQA 4.3.1.7 only says white blood cells 'respond quickly' and never names memory cells."],
["b2-antibiotics-resistance-vaccines","4.3.1.7;4.3.1.8;4.6.3.4","CB4.3;CB5.16;CB5.20","matched","high",
 "Painkillers and the full drug-development pathway including placebo and double-blind trials (AQA 4.3.1.8, 4.3.1.9)","",""],
["b2-non-communicable-diseases-cancer","4.2.2.5;4.2.2.6;4.2.2.7","CB2.4;CB5.2;CB5.23;CB5.24","matched","high",
 "Benign versus malignant tumours as named terms (AQA 4.2.2.7)","",""],
["b2-heart-attacks-strokes","4.2.2.4","CB5.25","matched","high","","",
 "Edexcel CB5.25 is an 'evaluate the treatments' statement, which matches CCEA's treatment-comparison questions closely."],
// ---------------- C1 ----------------
["c1-atomic-structure","5.1.1.1;5.1.1.3;5.1.1.4;5.1.1.5;5.1.1.7","CC1.1;CC1.2;CC1.3;CC1.4;CC1.5;CC1.6;CC1.19;CC1.20","matched","high",
 "The full history of the model of the atom including Bohr and Chadwick (AQA 5.1.1.3)","",""],
["c1-isotopes-relative-atomic-mass","5.1.1.6","CC1.7;CC1.8;CC1.9;CC1.10;CC1.11;CC1.12","matched","high","","",""],
["c1-ionic-bonding","5.2.1.2;5.2.1.3","CC1.21;CC1.22;CC1.23;CC1.24;CC1.26","matched","high","","",""],
["c1-covalent-bonding","5.2.1.4","CC1.28;CC1.29;CC1.31","matched","high","","",""],
["c1-ionic-and-molecular-structures","5.2.2.3;5.2.2.4","CC1.27;CC1.33;CC1.34","matched","high","","",""],
["c1-carbon-allotropes-nanoparticles","5.2.2.6;5.2.3.1;5.2.3.2;5.2.3.3","CC1.35;CC1.36;CC1.37;CC1.38","partial","high","",
 "Nanoparticles: AQA covers them in Chemistry 8462 only (4.2.4); Edexcel 1SC0 has no nanoparticle statement",""],
["c1-metallic-structures-classifying","5.2.1.5;5.2.2.7;5.2.2.8","CC1.32;CC1.40;CC1.42","matched","high","","",""],
["c1-symbols-and-formulae","5.1.1.1","CC1.25;CC1.26","matched","high","","",""],
["c1-word-and-balanced-equations","5.3.1.1;5.2.2.2","CC1.47","matched","high","","",""],
["c1-ionic-and-half-equations","5.4.3.5","CC3.27","matched","high","","",
 "AQA 5.4.3.5 is Higher only, as CCEA's outcome is."],
["c1-periodic-table-structure","5.1.2.1;5.1.2.2","CC1.13;CC1.14;CC1.15;CC1.16;CC1.17","matched","high","","",""],
["c1-metals-and-non-metals","5.1.2.3","CC1.18;CC1.42","matched","high","","",""],
["c1-group-1-alkali-metals","5.1.2.5","CC6.2;CC6.3;CC6.4;CC6.5","matched","high","","",""],
["c1-group-7-halogens","5.1.2.6","CC6.6;CC6.7;CC6.8;CC6.9;CC6.10;CC6.11;CC6.12;CC6.13","matched","high",
 "Hydrogen halides and their acidity (Edexcel CC6.10)","",""],
["c1-group-0-and-transition-metals","5.1.2.4","CC6.14;CC6.15;CC6.16","partial","high","",
 "Transition metals: AQA covers them in Chemistry 8462 only (4.1.3, chemistry only); Edexcel 1SC0 has no transition-metal statement",""],
["c1-formula-mass-and-moles","5.3.1.2;5.3.2.1","CC1.43;CC1.50;CC1.51","matched","high","",
 "AQA's mole statements (5.3.2.x) are Higher only; CCEA introduces the mole at Foundation in C1",""],
["c1-reacting-masses-and-yield","5.3.2.2;5.3.2.4","CC1.48;CC1.52;CC1.53","partial","high","",
 "Percentage yield: AQA covers it in Chemistry 8462 only (4.3.3); Edexcel 1SC0 has no percentage-yield statement",""],
["c1-indicators-and-ph","5.4.2.4","CC3.2;CC3.3;CC3.5","matched","high",
 "The factor-of-ten relationship between pH and hydrogen ion concentration (Edexcel CC3.5)","",""],
["c1-acids-alkalis-strength","5.4.2.4;5.4.2.5","CC3.1;CC3.4;CC3.7;CC3.8","matched","high","",
 "AQA 5.4.2.5 (strong and weak acids) is Higher only, matching CCEA's tiering",""],
["c1-neutralisation-and-bases","5.4.2.2","CC3.9;CC3.10;CC3.13;CC3.14","matched","high","","",""],
["c1-reactions-of-acids","5.4.2.1;5.8.2.1;5.8.2.3","CC3.11;CC3.12","matched","high","","",""],
["c1-salts-and-lab-safety","5.4.2.3","CC3.15;CC3.16;CC3.17","partial","high","",
 "GHS/CLP hazard symbols: zero hits in AQA 8464/8462 and Edexcel 1SC0",
 "AQA's soluble-salts required practical and Edexcel CC3.17 both match CCEA Prescribed Practical C1."],
["c1-purity-and-formulations","5.8.1.1;5.8.1.2","CC2.5;CC2.6","matched","high","","",""],
["c1-separating-mixtures-chromatography","5.1.1.2;5.8.1.3","CC2.7;CC2.8;CC2.9;CC2.10;CC2.11","matched","high",
 "Potable and waste water treatment (AQA 5.10.1.2, 5.10.1.3; Edexcel CC2.12)","",""],
["c1-flame-tests","8462:4.8.3.1","","ccea-only","high","",
 "Flame tests are in AQA Chemistry 8462 only (4.8.3.1) and in no Edexcel 1SC0 statement",
 "Against Combined Science this is CCEA-only; CCEA examines it as Prescribed Practical C2."],
// ---------------- C2 ----------------
["c2-reactivity-series","5.4.1.2","CC4.1;CC4.3","matched","high","","",""],
["c2-displacement-and-extraction","5.4.1.3;5.4.1.4","CC4.2;CC4.4;CC4.6;CC4.7","matched","high",
 "Biological extraction by bacteria and phytoextraction (Edexcel CC4.8; AQA 5.10.1.4, Higher)","",
 "AQA 5.4.1.4 (oxidation and reduction in terms of electrons) is Higher only."],
["c2-redox","5.4.1.1;5.4.1.4","CC3.28;CC3.29;CC4.5","matched","high","","",""],
["c2-rusting-and-iron","8462:4.10.3.1","CC4.9","partial","medium","",
 "Rusting and its prevention: AQA covers it in Chemistry 8462 only; Edexcel CC4.9 reaches only 'resistance to oxidation'. Blast-furnace extraction of iron is CCEA-specific detail",""],
["c2-measuring-rates","5.6.1.1","CC7.1;CC7.2;CC7.5","matched","high",
 "Drawing tangents to find rate at a point (AQA 5.6.1.1, Higher)","",
 "AQA required practical 11 and Edexcel Core Practical CC7.1 both match CCEA Prescribed Practical C4."],
["c2-collision-theory-catalysts","5.6.1.2;5.6.1.3;5.6.1.4","CC7.3;CC7.4;CC7.6;CC7.7","matched","high",
 "Pressure of reacting gases as a factor (AQA 5.6.1.2, Edexcel CC7.4); enzymes as biological catalysts in this topic (CC7.8)",
 "Manganese(IV) oxide named as the catalyst for hydrogen peroxide: zero hits in AQA 8464 and Edexcel 1SC0",""],
["c2-equilibrium","5.6.2.1;5.6.2.2;5.6.2.3","CC4.13;CC4.14","matched","high",
 "The effect of changing conditions on equilibrium (AQA 5.6.2.4 to 5.6.2.7, all Higher; Edexcel CC4.17) and the Haber process conditions (CC4.15, CC4.16)","",""],
["c2-homologous-series-alkanes","5.7.1.1;5.7.1.3","CC8.1;CC8.5;CC8.6","matched","high","","",""],
["c2-crude-oil-fractional-distillation","5.7.1.2;5.7.1.4","CC8.2;CC8.3;CC8.4;CC8.16;CC8.17","matched","high","","",""],
["c2-combustion-and-pollution","5.9.3.1;5.9.3.2","CC8.7;CC8.8;CC8.9;CC8.10;CC8.11;CC8.12;CC8.13;CC8.14","matched","high",
 "Hydrogen versus petrol as a fuel (Edexcel CC8.14)","",""],
["c2-alkenes","5.7.1.4","CC8.16","partial","high","",
 "Alkene reactions and the bromine-water test: AQA covers them in Chemistry 8462 only (4.7.2.2); Edexcel 1SC0 reaches alkenes only through cracking",""],
["c2-addition-polymerisation","8462:4.7.3.1","CC1.39","partial","medium","",
 "AQA covers addition polymerisation in Chemistry 8462 only; Edexcel CC1.39 uses poly(ethene) as a single example inside bonding",""],
["c2-alcohols-fermentation","8462:4.7.2.3","CC7.8","partial","medium","",
 "Alcohols as a homologous series are AQA Chemistry 8462 only; Edexcel 1SC0 mentions fermentation only inside CC7.8 (enzymes in alcoholic drinks)",""],
["c2-carboxylic-acids","5.4.2.5;8462:4.7.2.4","","partial","high",
 "Reactions of carboxylic acids with alcohols to form esters (AQA 8462 4.7.2.4); esters and their smells",
 "The homologous series itself - the -COOH group and the first four acids by name - is in AQA Chemistry 8462 only (4.7.2.4, an almost exact match for CCEA's list: methanoic, ethanoic, propanoic, butanoic) and in no Edexcel 1SC0 statement. Reactions with hydroxides and with metals are CCEA's own",
 "IMPORTANT: the WEAK ACID half IS in AQA Combined Science. 8464 5.4.2.5 (Higher only) defines a weak acid as 'only partially ionised in aqueous solution' and names ETHANOIC acid as an example, then adds the clause our Summer 2025 finding turns on - 'for a given concentration, the stronger an acid, the lower the pH' - which is exactly the partial-ionisation-versus-low-pH distinction candidates conflate. So the concept is matched and the organic chemistry is not."],
["c2-hydrated-salts-water-of-crystallisation","","CC1.45;CC1.46;CC3.17","partial","high","",
 "Water of crystallisation: zero hits in AQA 8464 and 8462. Edexcel reaches it only through the hydrated copper sulfate Core Practical (CC3.17) and empirical formulae (CC1.45, CC1.46)",
 "Edexcel CC3.17 is the nearest thing on any board to CCEA Prescribed Practical C5."],
["c2-concentration-atom-economy","5.3.2.5","CC1.49","partial","high","",
 "Atom economy: AQA covers it in Chemistry 8462 only (4.3.3.2); Edexcel 1SC0 has no atom-economy statement. Concentration itself is matched",""],
["c2-electrolysis-molten-salts","5.4.3.1;5.4.3.2;5.4.3.5","CC3.22;CC3.23;CC3.24;CC3.25;CC3.26;CC3.27","matched","high",
 "Electrolysis of aqueous solutions and of copper sulfate (AQA 5.4.3.4; Edexcel CC3.30, CC3.31)","",""],
["c2-aluminium-extraction","5.4.3.3","CC4.7;CC4.10","partial","high",
 "Life cycle assessment (Edexcel CC4.11, CC4.12; AQA 5.10.2.1)","",""],
["c2-energy-changes","5.5.1.1;5.5.1.2;5.5.1.3","CC7.9;CC7.10;CC7.11;CC7.12;CC7.13;CC7.14;CC7.15;CC7.16","matched","high","",
 "AQA 5.5.1.3 (bond energies) is Higher only; Edexcel CC7.14 is not tier-restricted",""],
["c2-atmosphere-nitrogen-ammonia","5.9.1.1","CC4.15;CC4.16;CC8.18;CC8.19;CC8.20;CC8.21;CC8.22","partial","high",
 "The Earth's early atmosphere in detail and the Haber process conditions","The ammonia test with damp red litmus paper: zero hits in AQA 8464 and Edexcel 1SC0",""],
["c2-hydrogen-oxygen-preparation","5.8.2.1;5.8.2.2","CC3.12;CC8.23","partial","high","",
 "Laboratory preparation of hydrogen and oxygen as an examined method is CCEA-specific; both other boards examine only the gas tests",""],
["c2-carbon-dioxide-preparation","5.8.2.3;5.9.2.1","CC3.12","partial","high","",
 "Laboratory preparation of carbon dioxide and its reaction with water: CCEA-specific; the other boards examine only the limewater test",
 "CCEA Prescribed Practical C6 has no AQA or Edexcel equivalent."],
// ---------------- P1 ----------------
["p1-speed-equations","6.5.4.1.2;6.5.4.1.5","CP2.6;CP2.8;CP2.11","matched","high",
 "Typical everyday speeds to be recalled (Edexcel CP2.12, CP2.13; AQA 6.5.4.1.2)","",
 "CCEA Prescribed Practical P1 (ramp) is closest to Edexcel CP2.11 (laboratory methods for determining speed)."],
["p1-vectors-velocity-acceleration","6.5.1.1;6.5.4.1.1;6.5.4.1.3","CP2.1;CP2.2;CP2.3;CP2.4;CP2.5","matched","high",
 "The equation v squared minus u squared = 2as (Edexcel CP2.9)","",""],
["p1-motion-graphs","6.5.4.1.4;6.5.4.1.5","CP2.7;CP2.10","matched","high",
 "Area under a velocity-time graph as distance (AQA 6.5.4.1.5, Higher; Edexcel CP2.10)","",""],
["p1-forces-and-resultant","6.5.1.2;6.5.1.4","CP9.1;CP9.3;CP9.4;CP9.5","matched","high",
 "Free-body force diagrams and resolution of forces as named skills (Edexcel CP9.3, CP9.4)","",""],
["p1-newtons-laws","6.5.4.2.1;6.5.4.2.2;6.5.4.2.3","CP2.14;CP2.15;CP2.19;CP2.23","matched","high",
 "Inertial mass (Edexcel CP2.22); circular motion and centripetal force (CP2.20, CP2.21); stopping distances and reaction time (AQA 6.5.4.3)","",""],
["p1-mass-weight-free-fall","6.5.1.3","CP2.16;CP2.17;CP2.18","matched","high","","",""],
["p1-hookes-law","6.5.3","CP15.1;CP15.2;CP15.3;CP15.5;CP15.6","matched","high",
 "Energy stored in a stretched spring, E = half k x squared (Edexcel CP15.4; AQA 6.5.3)","",
 "AQA required practical 6 and Edexcel Core Practical CP15.6 both match CCEA Prescribed Practical P2."],
["p1-pressure","8463:4.5.5.1.1","","ccea-only","high","",
 "Pressure = force / area is in AQA Physics 8463 only (4.5.5, physics only) and in no Edexcel 1SC0 statement",""],
["p1-moments","8463:4.5.4","","ccea-only","high","",
 "Moments, levers and gears are in AQA Physics 8463 only (4.5.4, physics only); zero hits in Edexcel 1SC0",
 "CCEA Prescribed Practical P3 (Principle of Moments) has no combined-science equivalent on either board."],
["p1-centre-of-gravity-stability","6.5.1.3","","partial","high","",
 "AQA names the centre of mass once, inside 6.5.1.3 Gravity; stability, toppling and the line of action are CCEA-only. Zero hits in Edexcel 1SC0",""],
["p1-density-kinetic-theory","6.3.1.1;6.3.1.2;6.3.3.1","CP14.1;CP14.2;CP14.3;CP14.4;CP14.5;CP14.12;CP14.13","matched","high",
 "Specific heat capacity and specific latent heat (AQA 6.3.2.2, 6.3.2.3; Edexcel CP14.7 to CP14.9); absolute zero and the kelvin scale (CP14.14, CP14.15)","",""],
["p1-energy-forms-conservation-efficiency","6.1.1.1;6.1.2.1;6.1.2.2","CP3.3;CP3.4;CP3.5;CP3.6;CP3.7;CP3.8;CP3.9;CP3.11;CP3.12","matched","high",
 "Thermal conductivity and wall thickness (Edexcel CP3.10)","",""],
["p1-energy-resources","6.1.3","CP3.13;CP3.14","matched","high","","",""],
["p1-work-and-power","6.1.1.2;6.1.1.4","CP8.5;CP8.6;CP8.12;CP8.13;CP8.14","matched","high","",
 "CCEA Prescribed Practical P4 (measuring personal power) has no AQA required practical or Edexcel core practical equivalent",""],
["p1-kinetic-and-potential-energy","6.1.1.2;6.1.1.3","CP3.1;CP3.2;CP8.8;CP8.9","matched","high","","",""],
["p1-atom-nucleus-isotopes","6.4.1.1;6.4.1.2;6.4.1.3","CP6.1;CP6.2;CP6.3;CP6.4;CP6.5;CP6.6;CP6.7;CP6.17","matched","high",
 "Electron energy levels and absorption or emission of radiation (Edexcel CP6.8)","",""],
["p1-radioactive-decay","6.4.2.1;6.4.2.2","CP6.10;CP6.11;CP6.15;CP6.16;CP6.18;CP6.20;CP6.22","matched","high",
 "Positron (beta plus) decay and neutron radiation (Edexcel CP6.10, CP6.19)","",""],
["p1-background-radiation-dangers-safety","6.4.2.4","CP6.12;CP6.13;CP6.14;CP6.29;CP6.31;CP6.32","matched","high",
 "Radiation dose in sieverts (AQA 6.6.2.3); the activity unit becquerel (Edexcel CP6.24)","",
 "The match is carried by Edexcel: CP6.12 and CP6.13 are background radiation in combined science, while AQA 8464's 6.4.2.4 is contamination and irradiation only and its background-radiation statement is Physics 8463 4.4.3.1. Radon is named by CCEA and by neither board"],
["p1-half-life","6.4.2.3","CP6.23;CP6.25;CP6.26;CP6.27","matched","high","","",""],
["p1-uses-of-radioactivity","8463:4.4.3.3","CP5.22","partial","high","",
 "Tracers, thickness control and smoke alarms return zero hits in all five specifications, and no board asks for a half-life to be CHOSEN to suit a use. Edexcel's only overlap is the gamma-ray uses inside CP5.22, filed under the electromagnetic spectrum rather than radioactivity; AQA's fuller treatment is Physics 8463 4.4.3.3 and is medical uses only",
 "Corrected 20 Sep 2026 from ccea-only/medium: CP5.22g names sterilising and cancer treatment, so there is a combined-science statement to mine, and 4.4.3.3 is the precise AQA home"],
["p1-nuclear-fission","8463:4.4.4.1","","ccea-only","high","",
 "Nuclear fission is in AQA Physics 8463 only (4.4.4, physics only); zero hits in Edexcel 1SC0",""],
["p1-nuclear-fusion","8463:4.4.4.2","","ccea-only","high","",
 "Nuclear fusion is in AQA Physics 8463 only (4.4.4, physics only); zero hits in Edexcel 1SC0",""],
// ---------------- P2 ----------------
["p2-wave-types-and-properties","6.6.1.1;6.6.1.2","CP4.1;CP4.2;CP4.3;CP4.4;CP4.5;CP4.6;CP4.17","matched","high",
 "Measuring the speed of sound in air and ripples on water (Edexcel CP4.7)","",""],
["p2-echoes-ultrasound-sonar-radar","8463:4.6.1.5","","ccea-only","high","",
 "Ultrasound, sonar and radar are in AQA Physics 8463 only (4.6.1.5, physics only and Higher only); zero hits in Edexcel 1SC0",""],
["p2-electromagnetic-spectrum","6.6.2.1;6.6.2.3;6.6.2.4","CP5.10;CP5.11;CP5.12;CP5.20;CP5.21;CP5.22","matched","high",
 "Radiation dose in sieverts (AQA 6.6.2.3); radio waves inducing oscillations (CP5.23)","",""],
["p2-reflection","8463:4.6.1.3","CP4.11;CP5.13","partial","medium","",
 "Reflection in a plane mirror as a construction is in AQA Physics 8463 only (4.6.1.3); Edexcel 1SC0 mentions reflection only in the list of absorb/transmit/refract/reflect",""],
["p2-refraction-and-dispersion","6.6.2.2","CP4.10;CP5.9;CP5.14","partial","high",
 "Wave-front diagrams as an assessed skill (AQA 6.6.2.2, Higher only); refractive index and Snell's law (Edexcel Physics 1PH0 only)",
 "Dispersion of white light by a prism: zero hits for 'dispersion' or 'prism' in AQA 8464, AQA 8463 and Edexcel 1SC0",
 "Refraction is Higher only in AQA Trilogy and Foundation in CCEA. Edexcel CP5.9 is a Core Practical matching CCEA Prescribed Practical P5."],
["p2-lenses-focal-length","8463:4.6.2.5","","ccea-only","high",
 "Magnification = image height / object height (AQA 8463 4.6.2.5); concave (diverging) lens ray diagrams",
 "Lenses are in AQA Physics 8463 only; zero hits for 'lens' in AQA 8464 and Edexcel 1SC0",
 "Edexcel covers lenses in GCSE Physics 1PH0 Topic 6 only; the 1PH0 statement number was not verified this session."],
["p2-lens-ray-diagrams","8463:4.6.2.5","","ccea-only","high",
 "Magnification as a calculation; concave lens ray diagrams; the lens equation",
 "Lenses are in AQA Physics 8463 only; zero hits for 'lens' in AQA 8464 and Edexcel 1SC0",
 "CCEA examines the camera, projector and magnifying-glass cases by name; 2.2.11 (virtual image) is Higher only."],
["p2-conductors-circuits-symbols","6.2.1.1","CP10.2;CP10.3","partial","high",
 "The diode and its one-way behaviour as a symbol to recognise (AQA 6.2.1.4); LDR and thermistor symbols",
 "The distinction between ELECTRON FLOW (negative to positive) and CONVENTIONAL CURRENT (positive to negative): 'conventional current' returns zero hits in AQA 8464, AQA 8463 and Edexcel 1SC0 (the only 'conventional' hits are in the nuclide-notation sections). Edexcel CP10.8 describes current as the rate of flow of charge but never contrasts the two directions. Cell polarity - that the long line of the cell symbol is positive - is likewise CCEA's own",
 "Symbols and meter placement are matched: AQA 6.2.1.1 is 'standard circuit diagram symbols' and Edexcel CP10.2 is 'draw and use electric circuit diagrams representing them with the conventional symbols'. The direction distinction is not."],
["p2-charge-current-cells","6.2.1.2","CP10.6;CP10.7;CP10.8;CP10.9","matched","high","","",""],
["p2-ohms-law-filament-lamp","6.2.1.3;6.2.1.4","CP10.13;CP10.17;CP10.18","matched","high",
 "Light-dependent resistors and thermistors (AQA 6.2.1.4; Edexcel CP10.19, CP10.20)","",
 "AQA required practical 15 and Edexcel Core Practical CP10.17 both match CCEA Prescribed Practical P6."],
["p2-series-parallel-rules","6.2.2","CP10.10;CP10.11;CP10.15","matched","high","","",""],
["p2-calculating-resistance","6.2.2","CP10.12;CP10.14;CP10.15","partial","high","",
 "Calculating the combined resistance of resistors in PARALLEL is beyond both combined-science specifications. AQA 8464 6.2.2 states in terms: 'Students are not required to calculate the total resistance of two resistors joined in parallel'; Edexcel CP10.14 is qualitative ('explain why ... the net resistance is decreased') and CP10.15 calculates series circuits only. CCEA requires R1/2 for two equal resistors at Foundation and 1/R = 1/R1 + 1/R2 at Higher",
 "Series combination (R = R1 + R2) is matched on both boards; the parallel calculation is not. AQA required practical 15 does include 'combinations of resistors in series and parallel', but as a measuring activity, not a calculation."],
["p2-resistance-length-heating","6.2.1.4;6.2.4.2","CP10.21;CP10.22;CP10.23;CP10.24;CP10.25;CP10.26","matched","high","","",""],
["p2-electrical-power-energy-cost","6.2.4.1;6.2.4.2","CP10.27;CP10.28;CP10.29;CP10.30;CP10.31;CP10.32;CP10.42","partial","high",
 "The National Grid and transformers (AQA 6.2.4.3; Edexcel CP13.6 to CP13.10); E = QV (AQA 6.2.4.2) and P = I squared R (AQA 6.2.4.1, Edexcel CP10.31); E = IVt (Edexcel CP10.27)",
 "The kilowatt-hour and the cost of electricity: zero hits for 'kilowatt', 'kWh' or 'cost of electricity' in AQA 8464, AQA 8463 and Edexcel 1SC0. CCEA requires energy (kWh) = power (kW) x time (h) and cost = kWh x price per unit",
 "E = P x t and P = I x V are matched on both boards; the domestic-billing half is CCEA-only."],
["p2-electricity-in-the-home","6.2.3.1;6.2.3.2","CP10.33;CP10.34;CP10.35;CP10.36;CP10.37;CP10.38;CP10.39;CP10.40;CP10.41","partial","high",
 "The potential differences between live, neutral and earth as numbers (Edexcel CP10.40); the dangers of a live-to-earth connection (CP10.41)",
 "DOUBLE INSULATION: zero hits for 'double insulat' in AQA 8464, AQA 8463 and Edexcel 1SC0, and our Summer 2024 finding says candidates could not explain why such an appliance needs no earth wire. CHOOSING A FUSE RATING from I = P / V and the 3 A / 5 A / 13 A set is also CCEA's own - Edexcel CP10.38 and CP10.39 explain what a fuse does and where it goes, but neither board asks for the rating to be selected. The CRO trace comparison for a.c. and d.c. is CCEA's too",
 "a.c. versus d.c., the live/neutral/earth roles, switches in the live wire and the function of fuses and circuit breakers are all matched (AQA 6.2.3.1-6.2.3.2; Edexcel CP10.33-CP10.41)."],
["p2-magnetism-electromagnets","6.7.1.1;6.7.1.2;6.7.2.1","CP12.1;CP12.2;CP12.3;CP12.4;CP12.5;CP12.6;CP12.7;CP12.8;CP12.9","matched","high",
 "The motor effect, Fleming's left-hand rule and F = BIl (AQA 6.7.2.2, 6.7.2.3, both Higher; Edexcel CP12.10 to CP12.13)","",""],
["p2-solar-system-satellites","8463:4.8.1.1;8463:4.8.1.3","","ccea-only","high",
 "Dwarf planets and the Milky Way as named objects (AQA 8463 4.8.1.1); the Higher circular-orbit relationships - gravity changing velocity but not speed, and the radius changing if the speed changes (4.8.1.3, HT only)",
 "Space physics is in AQA Physics 8463 only (4.8, physics only). Edexcel Topic 7 Astronomy is printed in the Combined Science specification as 'only found in the GCSE in Physics'",
 "AQA 4.8.1.3 is a close match for CCEA's gravity-provides-the-orbital-force statement and for the planets/moons/artificial-satellites comparison; 4.8.1.1 covers the Solar System's contents. Neither names asteroids or comets, which CCEA does."],
["p2-stars-and-fusion","8463:4.8.1.1;8463:4.8.1.2","","ccea-only","high",
 "Elements heavier than iron being produced in a supernova, and the supernova distributing them through the universe (AQA 8463 4.8.1.2) - CCEA says only that all naturally occurring elements except hydrogen were formed by fusion in stars",
 "Star formation and fusion in stars are in AQA Physics 8463 only; Edexcel Topic 7 Astronomy is Physics-only",
 "AQA 4.8.1.1 is the closest statement anywhere: the Sun formed from a nebula 'pulled together by gravitational attraction', dust and gas drawn together by gravity causing fusion, and the equilibrium between gravitational collapse and expansion due to fusion energy. That equilibrium sentence is CCEA's main-sequence stability idea, one topic early."],
["p2-life-cycle-of-stars","8463:4.8.1.2","","ccea-only","high",
 "Elements heavier than iron produced in a supernova (AQA 8463 4.8.1.2)",
 "Life cycles of stars are in AQA Physics 8463 only, and even there THE STAGES ARE NOT NAMED: 4.8.1.2 says only 'describe the life cycle of a star: the size of the Sun; much more massive than the Sun'. Searching AQA 8463 for 'protostar', 'main sequence', 'red giant', 'white dwarf', 'neutron star' and 'black hole' returns nothing except one use of 'supernova'. Every one of CCEA's named stages is therefore CCEA's own, as is the black-hole definition",
 "So the borrowed material here is a shape of argument, not content. This whole outcome is Higher only on CCEA."],
["p2-big-bang-evidence","8463:4.8.2","","ccea-only","high",
 "Galaxy recession speed increasing with distance; supernova observations since 1998 suggesting the expansion is accelerating; dark matter and dark energy (AQA 8463 4.8.2 and its introduction)",
 "Red shift and the Big Bang are in AQA Physics 8463 only (4.8.2), and CMBR is in NO specification at all: searching AQA 8463 for 'microwave background' and 'CMB' returns nothing, and Edexcel Topic 7 Astronomy is Physics-only. CCEA's age of the Universe (about 14 billion years) and its Higher cooling sequence - neutrons and protons, then nuclei, then hydrogen atoms - are likewise CCEA's own",
 "AQA 4.8.2's red-shift wording is a good model: an observed increase in wavelength from most distant galaxies, bigger the further away, providing evidence that space itself is expanding."],
];
