/**
 * Writes out/sw.js after `next build`: a plain service worker that precaches the exported app shell at
 * install (every page that is not a single topic or paper, the app assets, the manifests and the decks,
 * about 10 MB), serves same-origin requests cache-first (network-first for content/decks so republished
 * content wins), and never touches YouTube, PhET or ccea.org.uk. Topic pages, their RSC payloads, the
 * published content JSON and the paper pages (about 50 MB) are the on-demand set: kept as they are
 * visited, or fetched all at once when the learner asks for the full offline copy in Settings
 * (a `offline-copy:start` message to the worker; `offline-copy:status` reports how much is present).
 * Run: node scripts/build-sw.mjs   (part of `npm run build`)
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(ROOT, "out");
if (!fs.existsSync(OUT)) {
  console.error("out/ not found; run next build first");
  process.exit(1);
}

const files = [];
function walk(dir) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p);
    else files.push(p);
  }
}
walk(OUT);

const KEEP = /\.(html|js|css|json|woff2|svg|png|ico|webmanifest|txt)$/i;
const urls = files
  // Skip the nested __next.<segment>/ folders Next 16 exports; scripts/fix-export.mjs writes the flattened
  // copies the client actually requests, and those are precached below.
  .filter((f) => KEEP.test(f) && !f.endsWith("sw.js") && !/[\\/]__next\.[^\\/]*[\\/]/.test(f))
  .map((f) => "/" + path.relative(OUT, f).split(path.sep).join("/"))
  .map((u) => u.replace(/\/index\.html$/, "/"))
  // Keep only the RSC payloads a client-side navigation fetches (route tree + page segment, requested with
  // ?_rsc=… which the cache match ignores), so offline taps stay soft navigations instead of full reloads.
  .filter((u) => !u.endsWith(".txt") || /\/__next\.(_tree|[^/]*__PAGE__)\.txt$/.test(u));

// The on-demand set: single topic pages (and their RSC payloads), the published content, single paper pages.
const ON_DEMAND_RE = [/^\/learn\/[^/]+\/[^/]+\/[^/]+\//, /^\/content\//, /^\/papers\/[^/]+\//];
// Except Slides: the export builds a /learn/<subject>/<unit>/<topic>/slides/ route only for the topics that have Slides
// (src/lib/slides/ready.ts), and the hero's "Start the slides" is the way in, so each is precached with its RSC payloads.
// On demand, a topic page kept from one online visit offered a way in that led to Today offline (audit CQ-07).
const SLIDES_RE = /^\/learn\/[^/]+\/[^/]+\/[^/]+\/slides\//;
const onDemand = urls.filter((u) => ON_DEMAND_RE.some((re) => re.test(u)) && !SLIDES_RE.test(u));
const onDemandSet = new Set(onDemand);
const shell = urls.filter((u) => !onDemandSet.has(u));
const sizeOf = (u) => {
  let p = decodeURIComponent(u);
  if (p.endsWith("/")) p += "index.html";
  try {
    return fs.statSync(path.join(OUT, p)).size;
  } catch {
    return 0;
  }
};
const onDemandBytes = onDemand.reduce((n, u) => n + sizeOf(u), 0);

const version = new Date().toISOString().replace(/[-:.TZ]/g, "").slice(0, 14);
const sw = `/* Cairn service worker · ${version} · generated by scripts/build-sw.mjs */
const VERSION = "cairn-${version}";
const PRECACHE = ${JSON.stringify(shell)};
const ON_DEMAND = ${JSON.stringify(onDemand)};
const ON_DEMAND_BYTES = ${onDemandBytes};
const NEVER = [/youtube/, /ytimg/, /phet\\.colorado\\.edu/, /ccea\\.org\\.uk/, /googleapis/, /gstatic/];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(VERSION).then(async (cache) => {
      for (let i = 0; i < PRECACHE.length; i += 50) {
        await Promise.all(PRECACHE.slice(i, i + 50).map((u) => cache.add(u).catch(() => undefined)));
      }
    }).then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== VERSION).map((k) => caches.delete(k)))).then(() => self.clients.claim()),
  );
});

// The full offline copy: every on-demand URL not already in this version's cache, 20 at a time, with
// progress posted to every open page. A second request while one is running joins it.
let copying = null;
async function broadcast(msg) {
  const clients = await self.clients.matchAll({ includeUncontrolled: true });
  for (const c of clients) c.postMessage(msg);
}
async function present(cache) {
  const keys = await cache.keys();
  return new Set(keys.map((r) => new URL(r.url).pathname));
}
async function copyStatus() {
  const have = await present(await caches.open(VERSION));
  const cached = ON_DEMAND.filter((u) => have.has(u)).length;
  return { type: "offline-copy:status", version: VERSION, cached, total: ON_DEMAND.length, bytes: ON_DEMAND_BYTES, copying: !!copying };
}
async function copyAll() {
  const cache = await caches.open(VERSION);
  const have = await present(cache);
  const todo = ON_DEMAND.filter((u) => !have.has(u));
  let done = ON_DEMAND.length - todo.length;
  let failed = 0;
  for (let i = 0; i < todo.length; i += 20) {
    await Promise.all(todo.slice(i, i + 20).map((u) => cache.add(u).then(() => { done++; }, () => { failed++; })));
    await broadcast({ type: "offline-copy:progress", version: VERSION, done, total: ON_DEMAND.length, failed });
  }
  await broadcast({ type: "offline-copy:done", version: VERSION, done, total: ON_DEMAND.length, failed });
}
self.addEventListener("message", (event) => {
  const data = event.data && typeof event.data === "object" ? event.data : {};
  if (data.type === "offline-copy:start") {
    if (!copying) copying = copyAll().finally(() => { copying = null; });
    event.waitUntil(copying);
  } else if (data.type === "offline-copy:status") {
    event.waitUntil(copyStatus().then((s) => (event.source ? event.source.postMessage(s) : broadcast(s))));
  }
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;            // external: browser default
  if (NEVER.some((re) => re.test(url.href))) return;
  const contentLike = url.pathname.startsWith("/content/") || url.pathname.startsWith("/decks/");
  if (contentLike) {
    // network-first so republished content is picked up; fall back to cache offline
    event.respondWith(fetch(req).then((res) => { const copy = res.clone(); caches.open(VERSION).then((c) => c.put(req, copy)); return res; }).catch(() => caches.match(req)));
    return;
  }
  // app shell and assets: cache-first, then network (and cache it), then the offline shell for navigations
  event.respondWith(
    caches.match(req, { ignoreSearch: true }).then((hit) => hit || fetch(req).then((res) => {
      if (res.ok) { const copy = res.clone(); caches.open(VERSION).then((c) => c.put(req, copy)); }
      return res;
    }).catch(() => (req.mode === "navigate" ? caches.match("/") : undefined))),
  );
});
`;
fs.writeFileSync(path.join(OUT, "sw.js"), sw);
console.log(
  `out/sw.js written: ${shell.length} precached URLs, ${onDemand.length} on demand (${(onDemandBytes / 1048576).toFixed(1)} MB), version ${version}`,
);
